### ISSUE TITLE
Fails to run

### ISSUE THREAD

**Issue by dyle71** [gateway-services/collectjs-react-demo#35]
Doing a `yarn install` and then a `yarn run start` fails with
```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/home/dyle/Source/other/collectjs-react-demo/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/dyle/Source/other/collectjs-react-demo/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/dyle/Source/other/collectjs-react-demo/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/dyle/Source/other/collectjs-react-demo/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/dyle/Source/other/collectjs-react-demo/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/dyle/Source/other/collectjs-react-demo/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/dyle/Source/other/collectjs-react-demo/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/dyle/Source/other/collectjs-react-demo/node_modules/babel-loader/lib/index.js:55:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.4.0
```

Node version is v20.4.0 (as stated in output).

```
yarn -v
3.6.1
```

Seems the openssl is not working properly (any more).

**Comment by tarun080698** [comment]
#36
